pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "lumungus-mods"

include(":lumungus-core")
include(":lumungus-storage")
include(":lumungus-backpack")
include(":lumungus-machines")
include(":lumungus-autotrader")
include(":lumungus-integration")

project(":lumungus-core").projectDir = file("modules/lumungus-core")
project(":lumungus-storage").projectDir = file("modules/lumungus-storage")
project(":lumungus-backpack").projectDir = file("modules/lumungus-backpack")
project(":lumungus-machines").projectDir = file("modules/lumungus-machines")
project(":lumungus-autotrader").projectDir = file("modules/lumungus-autotrader")
project(":lumungus-integration").projectDir = file("modules/lumungus-integration")
