org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric 26.2 toolchain
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.158.0+26.2

# Mod
mod_version=0.7.0-beta.28
maven_group=de.djdaddy
archives_base_name=rail-quarry
lumungus_version=0.1.0-uat.60
