dependencies {
    implementation project(":lumungus-core")
    implementation project(":lumungus-storage")

    testImplementation "org.junit.jupiter:junit-jupiter:${junit_version}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junit_version}"
}

tasks.named("test") {
    useJUnitPlatform()
}
